"""Initial migration

Revision ID: d5ca1528eaac
Revises: 
Create Date: 2024-11-10 16:44:57.960948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ca1528eaac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_location', sa.String(), nullable=True),
    sa.Column('arrival_location', sa.String(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_arrival_location'), 'rides', ['arrival_location'], unique=False)
    op.create_index(op.f('ix_rides_departure_location'), 'rides', ['departure_location'], unique=False)
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_departure_location'), table_name='rides')
    op.drop_index(op.f('ix_rides_arrival_location'), table_name='rides')
    op.drop_table('rides')
    # ### end Alembic commands ###
