openapi: 3.0.0
info:
  title: CampusRide API
  version: 1.0.0
  description: A simple ride-sharing service for students

paths:
  /rides/:
    get:
      summary: List all rides
      responses:
        "200":
          description: List of all rides
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ride"
    post:
      summary: Create a new ride
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RideCreate"
      responses:
        "201":
          description: Ride created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ride"
        "422":
          description: Validation Error

  /rides/{ride_id}:
    get:
      summary: Get a specific ride
      parameters:
        - name: ride_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Ride details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ride"
        "404":
          description: Ride not found

    put:
      summary: Update a ride
      parameters:
        - name: ride_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RideUpdate"
      responses:
        "200":
          description: Ride updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ride"
        "404":
          description: Ride not found
        "422":
          description: Validation Error

    delete:
      summary: Delete a ride
      parameters:
        - name: ride_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Ride deleted successfully
        "404":
          description: Ride not found

components:
  schemas:
    RideBase:
      type: object
      required:
        - departure_location
        - arrival_location
        - departure_time
        - available_seats
        - driver_name
      properties:
        departure_location:
          type: string
          minLength: 2
          maxLength: 100
        arrival_location:
          type: string
          minLength: 2
          maxLength: 100
        departure_time:
          type: string
          format: date-time
        available_seats:
          type: integer
          minimum: 1
          maximum: 8
        driver_name:
          type: string
          minLength: 2
          maxLength: 50

    RideCreate:
      allOf:
        - $ref: "#/components/schemas/RideBase"

    RideUpdate:
      type: object
      properties:
        departure_location:
          type: string
          minLength: 2
          maxLength: 100
        arrival_location:
          type: string
          minLength: 2
          maxLength: 100
        departure_time:
          type: string
          format: date-time
        available_seats:
          type: integer
          minimum: 1
          maximum: 8
        driver_name:
          type: string
          minLength: 2
          maxLength: 50

    Ride:
      allOf:
        - $ref: "#/components/schemas/RideBase"
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
